### PR TITLE
infinite scroll

### PR DESCRIPTION
**Pull request by ChoukseyKhushbu**
This PR has implemented infinite scrolling according to the pagination of GitHub API. But now the skills are getting added as the repositories are fetched.
Will fix this issue soon using graphql API.

### CODE REVIEW

**Comment by ChoukseyKhushbu** [comment]
Fixed #23

**Comment by BaseMax** [comment]
demo

Are you sure?

**Comment by ChoukseyKhushbu** [comment]
Hey @BaseMax,
Actually, right now I deployed the code in dev branch as it is in development as of now.
You can check it here -  https://dev--gitzilla.netlify.app/
I should have mentioned it before!

**Comment by ChoukseyKhushbu** [comment]
Hey @BaseMax,
Actually I have deployed it on dev as the feature is still in development.
You can check it here- https://dev--gitzilla.netlify.app/users/BaseMax
I should have mentioned it before. :sweat_smile:

**Comment by BaseMax** [comment]
Your work was excellent. @ChoukseyKhushbu 
Good job. :+1:

**Comment by ChoukseyKhushbu** [comment]
Thank you @BaseMax :smile:

**Pull request merged**
