### PR TITLE
[Chore] Migration of RESTAPI to GraphQL

### PR DESCRIPTION
**Pull request by ming-tsai**
- Change user and repos request to GraphQL
- Allow RepoCard display more than one language

### Dev evidence
**User profile**
image

**Repositories**
image

### CODE REVIEW

**Comment by ming-tsai** [comment]
Hi @ChoukseyKhushbu, should I merge to **master** or to **dev**

**Comment by ChoukseyKhushbu** [comment]
Hi @ming-tsai, Really great work from your side. :tada: 
No worries regarding the branch for merging as I can change it. Also, the deploy preview is set for both branches. 
Once I review your code I will merge it accordingly.
Thanks for your contribution. :hugs:

**Comment by ming-tsai** [comment]
Hi @ChoukseyKhushbu, please download the last version, I have had extract all queries to the `queries.js` file.

**Comment by ChoukseyKhushbu** [comment]
Hi @ming-tsai, 
The pagination was not implemented properly. 
It was paginating over and over again.
I have fixed the issue and merged the branch. :v: 
Thank you. :hugs:

**Comment by ming-tsai** [comment]
Thanks for helping me 🙌

**Pull request merged**
