### PR TITLE
Add website image to README.md

### LINKED ISSUE #43: Add a screenshot of the project to the README
Hi everyone 👋,

**Description**:
This project's `README` looks great, but what does everyone think about adding a screenshot of the app, to showcase it before anyone clicks on the link to visit the live app?

Something like this:
imagem

Or the result of someone's resume after inputting their profile. 

**Objective**:
This way a new contributor or user looking at the project, gets a glimpse of what your project does, and how it looks 😃

PS: This was an idea from Eddie on [this YouTube video](https://youtu.be/N34ViIk0C0k?t=180) 😄

### PR DESCRIPTION
**Pull request by bloodzmoon**
I've captured the website and added it in the `README.md` via relative path

PS. This is my very first time pull request to the open source 😅

### CODE REVIEW

**Comment by ChoukseyKhushbu** [comment]
Hey @bloodzmoon! Thank you for creating the PR.
I am glad that Gitzilla helped you in your very first open source PR :tada: :smile:.
Though I would like to have a few more enhancements -
- Adding mobile view screenshot as well.
- It will be great if you can add a screenshot template (for mobile and web both) :sweat_smile:  
Can refer to this for that - https://www.labnol.org/internet/take-mobile-screenshots/28167/

**Review by ChoukseyKhushbu — CHANGES_REQUESTED** [review]
Add photo-realistic screenshots for both mobile and web.

**Comment by bloodzmoon** [comment]
> Hey @bloodzmoon! Thank you for creating the PR.
> I am glad that Gitzilla helped you in your very first open source PR 🎉 😄.
> Though I would like to have a few more enhancements -
> 
> * Adding mobile view screenshot as well.
> * It will be great if you can add a screenshot template (for mobile and web both) 😅
>   Can refer to this for that - https://www.labnol.org/internet/take-mobile-screenshots/28167/

Okay I'll do this! By the way thank you for the opportunity 😉

**Comment by bloodzmoon** [comment]
Is this image okay? I'm not sure haha if it's not I can change it.

**Comment by ChoukseyKhushbu** [comment]
> Is this image okay? I'm not sure haha if it's not I can change it.

It looks good, but I guess, the background stuff is just taking too much attention, the mobile is not even visible that much.
Having just the screens would also work.

**Comment by bloodzmoon** [comment]
> > Is this image okay? I'm not sure haha if it's not I can change it.
> 
> It looks good, but I guess, the background stuff is just taking too much attention, the mobile is not even visible that much.
> Having just the screens would also work. 😅

Okay I'll change it to cleaner template 😄

**Comment by bloodzmoon** [comment]
Is this image okay now? Sorry for my bad art sense 😓 I can change again and again If this image isn't okay

**Review by ChoukseyKhushbu — APPROVED** [review]
This looks great! :smile: :partying_face:

**Comment by ChoukseyKhushbu** [comment]
> Is this image okay now? Sorry for my bad art sense  I can change again and again If this image isn't okay

No need to be sorry @bloodzmoon! We all learn! Thank you for updating the requested changes!
And welcome to open source :partying_face:!

**Pull request merged**
